[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api"
  to = "/.netlify/functions/chat"
  status = 200

[[redirects]]
  from = "/speak"
  to = "/.netlify/functions/speak"
  status = 200
